### ISSUE TITLE
It is lagging after two emojis are generated 

### ISSUE THREAD

**Issue by hurrrsh** [Pondorasti/emojis#11] opened 2023-10-07 05:55 UTC
SO i generated two emojis using the generator, as i try to do it third time the screen freezes . I refreshed the screen and entered the prompt again, it still isn't working

**Comment by pondorasti** [comment] 2023-10-07 08:07
Hey @Harshnatuskar, I'm having a hard time reproducing this. I've noticed that the collision rate with the current dataset was 1% which could have been the cause of your issue (fixed in https://github.com/Pondorasti/emojis/commit/998f600f02e77184eb61f1d41cf833da89f491e6).

If you are still experiencing this, could you please attach some more details (screen recording, console logs, network logs, etc). 🙏

**Closed as completed** 2023-10-09 04:02 UTC
